paths:
  static: ''
  uploads: uploads
timezone: Asia/Calcutta
markdown:
  engine: commonmark
  options: {}
source: /
collections_config:
  animated_design:
    path: animated/design
    icon: animated_images
